### PR TITLE
fix: restore previous implementation and remove getServerUser from Edge

### LINKED ISSUE #93: Fix: deploy

### PR DESCRIPTION
**Pull request by NatashaSolntseva**
### 1. **Task/Issue Reference**

**Task:** [Fix: deploy](https://github.com/petruse4ka/rest-client-app/issues/93)

### 2. **Changes Made**

- [x] Reverted middleware to an Edge-safe version; removed getServerUser and all firebase-admin imports from middleware.ts
- [x] Fix missing header in REST Client
- [ ] Fix handling of invalid/corrupted session cookie

### 4. **Testing**

**Local Testing:**

- [x] Changes have been tested locally
- [x] All existing functionality still works
- [x] New functionality works as expected
- [x] No console errors or warnings

**Test Coverage:**

- [ ] Tests have been added for new functionality
- [x] Existing tests still pass
- [x] Tests are not required in this case

### 5. **Code Quality**

- [x] Code follows project style guidelines
- [x] No linting errors or warnings
- [x] No magic strings/numbers hardcoded values or sensitive information

### 6. **Review Process**

- [x] Proper reviewers have been assigned
- [ ] All feedback has been addressed

### CODE REVIEW

**Review by petruse4ka — APPROVED** [review]
The code looks good to me.

I have briefly tested the implementation as a user and could not find anything worrying. I believe we can merge it, considering that the deploy does not work otherwise, and we should test everything extensively once again.

**Review by tearzday — APPROVED** [review]
Good

File: src/middleware.ts [hunk 1]
```diff
@@ -25,18 +25,33 @@ export async function middleware(req: NextRequest) {
...
+        method: 'POST',
+        headers: { 'Content-Type': 'application/json' },
+        body: JSON.stringify(session),
+      });
+
+      isValid = res.ok;
+    } catch {
+      return null;
+    }
+  }
```
Comment (NatashaSolntseva) [inline src/middleware.ts:47]: This may not be the perfect pattern, but it covers all tested token manipulation scenarios; I suggest we keep it for now and revisit if needed.
